### PR TITLE
simple-call-tree-display-buffer doesn't work after the cl-lib transition

### PR DESCRIPTION
**Pull request by rexim**
It's generally better to depend on `cl-lib` rather than on `cl`, but for some reason after de02ed117727ac76c45cd7e89dc51895744787d2 the `simple-call-tree-display-buffer` function doesn't work for me anymore. If it doesn't work for you as well I suggest to revert the commit and perform transition to `cl-lib` incrementally. I can help you with that if you don't have time.

**Environment**: Linux, Emacs 24.5.1

**Reproduction steps**:
- Install the latest simple-call-tree via MELPA
- Open `simple-call-tree.el`
- Do `M-x simple-call-tree-display-buffer RET`
- Answer `n` to `Include other files?`

**Observed**: a message "simple-call-tree done" in the `*Messages*` buffer. No `*Simple Call Tree*` buffer created.

**Expected**: `*Simple Call Tree*` buffer created with the call tree for the current buffer.

I can achieve the expected behavior by reverting de02ed117727ac76c45cd7e89dc51895744787d2

Regards,
rexim

**UPD.** Looks like we need only revert only the changes that are related to `cl-position` (thanks to @jonmoore). But it remains unclear what exactly wrong with `cl-position`. Updated the PR accordingly.

**UPD2.** everything's fine with the `cl-position` function. Apparently the `position` symbol was used not only in the function call places. And the entire cl-lib transition was made with a straightforward text replacement. So this is how the whole problem was created. Updated the PR accordingly.

### CODE REVIEW

**Comment by jonmoore** [comment]
What's happened is that where `position` was used to describe the sort method (as in `simple-call-tree-default-sort-method`) this has been replaced by `cl-position` in some cases.  Reverting back to `position` at these points fixes the problem.

**Comment by rexim** [comment]
@jonmoore that's interesting... Let me check that and update the PR. Thanks!

**Comment by rexim** [comment]
@jonmoore wow! You're right! But why so? Documentation says that `position` is an alias for `cl-position` in `cl.el`. Interesting...

**Comment by jonmoore** [comment]
I think just changing at lines 704, 836 and 1338 is enough, since that's where `position` is being used as a symbol as far as I can see.  That will still keep the function calls to `cl-position`, in line with the change to `cl-lib`.

**Comment by rexim** [comment]
@jonmoore ah, I think I finally got it! Thanks for your patience. I read other people's comments carelessly quite often. Let me fix the PR again. :)

**Comment by rexim** [comment]
@vapniks could you please take a look at this PR when you get a chance?

**Comment by vapniks** [comment]
Done.

**Comment by rexim** [comment]
@vapniks thank you very much!

**Pull request merged**
